Updates
23watejona/robotics-command-parser pull request #3
Opened 2023-06-29 23:26 UTC by Gold856

2023-07-05 21:24 UTC, 23watejona requested changes

2023-07-05 21:24 UTC, 23watejona commented on grammarGenerator.js
Is there a better way to do this? (There is...)

2023-07-05 21:24 UTC, 23watejona commented on index.js
These are intentionally separated - you can reuse the command list for multiple files with different methods in each

2023-07-05 21:24 UTC, 23watejona commented on test/test.js
See comment on index

2023-07-05 21:24 UTC, 23watejona commented on test/testScript.txt
> -
not sure exactly why this file is changed

2023-07-05 21:24 UTC, 23watejona commented on .gitattributes
> -* text=auto
why?...

2023-07-05 21:32 UTC, Gold856 commented on .gitattributes
> -* text=auto
`* text=auto` doesn't force LF line endings. I have `core.autocrlf` enabled in my Git settings, so it auto converted it to CRLF's. To force LF's, you need the extra `eol=lf` bit

2023-07-05 21:33 UTC, Gold856 commented on test/testScript.txt
> -
The tests failed without it. Sidenote, your error report doesn't give an accurate line number of where the error is.

2023-07-05 21:34 UTC, Gold856 commented on grammarGenerator.js
What's the problem here? It's not that bad

2023-07-05 21:50 UTC, 23watejona commented on grammarGenerator.js
I meant to do the parameter naming. Hint: use the existing array.map

2023-07-05 21:50 UTC, Gold856 commented on grammarGenerator.js
There is a much better way to do that

2023-07-05 22:49 UTC, 23watejona requested changes

2023-07-05 22:49 UTC, 23watejona commented on index.js
> +	return grammarGenerator.generateGrammar(commandList.commands, functionList)
Why is this necessary?

2023-07-05 22:49 UTC, 23watejona commented on test/testScript.txt
> -
I don't like this answer - can you figure out why this is?

2023-07-05 22:57 UTC, Gold856 commented on index.js
> +	return grammarGenerator.generateGrammar(commandList.commands, functionList)
Commands are wrapped in a root `commands` key.

2023-07-05 23:07 UTC, 23watejona requested changes

2023-07-05 23:07 UTC, 23watejona commented on index.js
> +	return grammarGenerator.generateGrammar(commandList.commands, functionList)
But why? It's implied in the file

2023-07-05 23:07 UTC, Gold856 commented on test/testScript.txt
> -
Well I can tell you the line number inaccuracy is due to new lines in Java blocks not being counted

2023-07-05 23:31 UTC, 23watejona commented on test/testScript.txt
> -
I know the line errors are wrong... I meant why you needed to change the spacing there

2023-07-05 23:56 UTC, 23watejona requested changes

2023-07-05 23:56 UTC, 23watejona commented on test/testcommandlist.json
>  {
Remove unnecessary wrapper plz

2023-07-06 00:43 UTC, 23watejona approved these changes

2023-07-06 00:44 UTC, merged